swagger: "2.0"
info:
  description: Garden Layout Solver
  version: "1.0.0"
  title: Garden Layout Solver
consumes:
  - application/json
produces:
  - application/json

# Paths supported by the server application
paths:
  /:
    get:
      operationId: liveness.is_alive
      tags:
        - Liveness
      summary: Check application status
      description: Check application status
      responses:
        200:
          description: Successfully check liveness

  /layout/recommend:
    post:
      operationId: layout.recommend
      tags:
        - Layout
      summary: Recommend garden layout
      description: Recommend garden layout based on user specification
      parameters:
        - name: specification
          in: body
          schema:
            $ref: '#/definitions/GardenLayoutSpecification'
      responses:
        200:
          description: List of garden layout

definitions:
  GardenLayoutSpecification:
    type: object
    required:
      - garden
    properties:
      garden:
        $ref: '#/definitions/GardenSpecification'
        description: Garden specification
      wanted_proposals:
        type: integer
        description: Number of proposals wanted
        example: 10
  GardenSpecification:
    type: object
    required:
      - width
      - height
    properties:
      width:
        type: number
        description: Garden width
        example: 5.5
      height:
        type: number
        description: Garden height
        example: 3.5


